### ISSUE TITLE
Title bar icons are too small

### ISSUE THREAD

**Issue by Batandwa-mgutsi** [bitsdojo/bitsdojo_window#1]
Hi @bitsdojo, really nice package you have here. However, the minimize, maximize, and close buttons are too small on my PC. They are much smaller than those of the other windows. I'm certain I am not doing anything wrong that might mess with the size, but please help me out if I am. 

I took a look at `getTitleBarButtonSize()` in `window_caption.dart` and noticed it uses the device-dependent pixel values returned by `GetSystemMetrics(int)`. Shouldn't these be converted to logical pixels?

This is the code I used to render my title bar
```dart
class WindowTitleBarView extends StatelessWidget {
  final Widget body;
  WindowTitleBarView({this.body, Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Container(
      color: appColors.kcSweetsAppBarColor,
      child: Column(
        children: [
          WindowTitleBarBox(
            child: Row(
              children: [
                Expanded(child: MoveWindow()),
                Row(
                  children: [
                    MinimizeWindowButton(colors: _windowButtonColors),
                    MaximizeWindowButton(colors: _windowButtonColors),
                    CloseWindowButton(colors: _windowCloseButtonColors),
                  ],
                )
              ],
            ),
          ),
          Expanded(child: body),
        ],
      ),
    );
  }
}
```
And this is how small the buttons look in my window:
![image](https://user-images.githubusercontent.com/22795741/100770837-62627580-3406-11eb-8d8f-aa3016afe868.png)

**Comment by technolion** [comment]
I can also reproduce this on Windows 10 with a screen resolution of 3440 x 1440:
![title-icons-too-small](https://user-images.githubusercontent.com/1611505/101054518-44714e00-3589-11eb-8000-e891f2562bfb.png)

**Comment by bitsdojo** [comment]
Just pushed 0.0.3. Could you please try it and let me know how it goes?

**Comment by technolion** [comment]
Yeah, looks great now!
![Bildschirmfoto 2020-12-03 um 17 20 29](https://user-images.githubusercontent.com/1611505/101057031-e3974500-358b-11eb-98c5-48885ae794cc.png)

**Comment by bitsdojo** [comment]
Great! Thanks!
