### ISSUE TITLE
Support Run web with Dektop

### ISSUE THREAD

**Issue by mstfkhazaal** [bitsdojo/bitsdojo_window#10]
When I add WindowsTitleBar, the web version just doesn't work 
This Code : https://github.com/mstfkhazaal/windows_title_bar/

Note: On the android it work perfectly

And Please Add rounded Border

https://user-images.githubusercontent.com/47450090/102693891-6a078400-4226-11eb-8d34-09efd6453863.mp4

**Comment by ArinFaraj** [comment]
The package depends on win32 package so i don't know if it's possible to make it compatible with web.

There is a way to exclude files from building when you target web using `build.yaml` but i haven't had time to look into it. 

Maybe try excluding the entire package from building and use platform checks eleminate the need for the files related to this package.

Obviously I'm not sure this would be possible or if it would work but its a starting point.

**Comment by bitsdojo** [comment]
Thank you for reporting this! I am currently transitioning the plugin to a federated one (with separate packages for each platform) and that should fix the issue.

**Comment by bitsdojo** [comment]
Fixed by https://github.com/bitsdojo/bitsdojo_window/commit/814ac4ed811f4398a9cebd771f4767f63034fd63
