### ISSUE TITLE
Many symbols have external linkage without namespacing

### ISSUE THREAD

**Issue by stuartmorgan** [bitsdojo/bitsdojo_window#13]
Substantial portions of the C++ code here use external linkage, and have generic names, which makes collisions between plugins trivial.

Example STR:
1. Someone inspired by this plugin copies it as a starting point for another plugin that modifies window creation in other ways.
1. They carefully rename everything containing "bitsdojo" to their own plugin's name, and replace much of the logic, but keep the core window proc hooking mechanics from this plugin.
1. They test, everything works and they publish it.
1. Some Flutter developer tries to use both bitsdojo_window and that plugin.

Expected results:
- Everything works.

Actual results:
- Their app fails to compile:
```
error LNK2005: "struct HWND__ * flutter_window" (?flutter_window@@3PEAUHWND__@@EA) already defined in bitsdojo_window_plugin.lib(bitsdojo_window.obj)
error LNK2005: "struct HHOOK__ * flutterWindowMonitor" (?flutterWindowMonitor@@3PEAUHHOOK__@@EA) already defined in bitsdojo_window_plugin.lib(bitsdojo_window.obj)
error LNK2005: "__int64 __cdecl main_window_proc(struct HWND__ *,unsigned int,unsigned __int64,__int64,unsigned __int64,unsigned __int64)" (?main_window_proc@@YA_JPEAUHWND__@@I_K_J11@Z) already defined in bitsdojo_window_plugin.lib(bitsdojo_window.obj)
error LNK2005: "__int64 __cdecl monitorFlutterWindowsProc(int,unsigned __int64,__int64)" (?monitorFlutterWindowsProc@@YA_JH_K_J@Z) already defined in bitsdojo_window_plugin.lib(bitsdojo_window.obj)
error LNK2005: "void __cdecl monitorFlutterWindows(void)" (?monitorFlutterWindows@@YAXXZ) already defined in bitsdojo_window_plugin.lib(bitsdojo_window.obj)
```

It's unexpected that using a plugin would prevent all other use of extremely generic symbol names like `flutter_window` throughout the app (including any other static libraries), and it's unnecessary since these symbols could all have internal linkage.

(Hopefully this is specific enough that you don't consider it "vaguely mentioning potential situations with low possibility of happening in the future".)

**Comment by bitsdojo** [comment]
This is a good point and I appreciate the specific STR.

I have just pushed an update that should fix this issue.

Thank you!
