### ISSUE TITLE
[WINDOWS]  BDW_CUSTOM_FRAME ERROR : Error waiting for a debug connection

### ISSUE THREAD

**Issue by oubadaalkahf** [bitsdojo/bitsdojo_window#130]
![error](https://user-images.githubusercontent.com/80518104/152844945-ce8bb788-10f4-4c69-8373-a8fc37e9db80.PNG)
Error happen after adding this follow line : auto bdw = bitsdojo_window_configure(BDW_CUSTOM_FRAME | BDW_HIDE_ON_STARTUP);
exactly because of BDW_CUSTOM_FRAME 
need help please!!

**Comment by CodeDoctorDE** [comment]
Duplicate of #129

**Comment by oubadaalkahf** [comment]
it works , thank you
