### ISSUE TITLE
Next pub.dev release date?

### ISSUE THREAD

**Issue by longtimedeveloper** [bitsdojo/bitsdojo_window#137]
Hi @bitsdojo,

Do you have a date for your next pub.dev release?  There is a lot of work in this repro that is not in the current pub.dev release.

For example, your Example Code at [https://github.com/bitsdojo/bitsdojo_window/tree/master/bitsdojo_window/example](https://github.com/bitsdojo/bitsdojo_window/tree/master/bitsdojo_window/example) does not work when using the pub.dev release because `RestoreWindowButton` is not in the pub.dev release.

Thank you and have a splendid day, Karl

**Comment by bitsdojo** [comment]
Just pushed `0.1.2` to pub.dev so closing this.
