### ISSUE TITLE
Latest updates

### ISSUE THREAD

**Issue by bitsdojo** [bitsdojo/bitsdojo_window#140]
Hi everyone,

I've been offline in the past month and a half due to a medical issue but I will have access to my computer next week and I will take a look over the issues.

Bit

**Comment by CodeDoctorDE** [comment]
By the way: You are featured on the flutter.dev site https://docs.flutter.dev/development/ui/layout/building-adaptive-apps#title-bars

**Comment by CodeDoctorDE** [comment]
Hi do you have any updates?

**Comment by bitsdojo** [comment]
I'm back so closing this.
