### ISSUE TITLE
Set window size to widget size.

### ISSUE THREAD

**Issue by bradleybauer** [bitsdojo/bitsdojo_window#152]
Is it possible to set the window size to be the size of my main content widget? I am using a fork of bitsdojo_window to remove the system titlebar and border. My main content is resizable (collapsible and expandable lists). I think it would look great if my app window resized with the content. Can this be done with a plugin?

**Comment by appinteractive** [comment]
Can't you just set the window size to the widget size? There are widgets that give you the size on change, there you could update the window size.

For example: https://pub.dev/packages/measure_size

**Comment by bradleybauer** [comment]
Yeah that does work. TBH I did not look into this very much before submitting the issue.

measure_size does not trigger it's callback when I expect it to. But I can work around that.
