### ISSUE TITLE
No such module 'bitsdojo_window_macos'

### ISSUE THREAD

**Issue by bmcpt** [bitsdojo/bitsdojo_window#159]
I'm getting the above mentioned error when trying to build an archive using Xcode.

I'm using the following instructions: https://docs.flutter.dev/deployment/macos

This is a screenshot of the error:
![Screenshot 2022-04-07 at 6 47 10 PM](https://user-images.githubusercontent.com/99397878/162208210-dc521975-9fe1-4973-b421-12859dfdbc84.png)

**Comment by gOATiful** [comment]
same issue
