### ISSUE TITLE
Support macOS

### ISSUE THREAD

**Issue by cbenhagen** [bitsdojo/bitsdojo_window#16]
Planned support for macOS is mentioned in the README. I am opening this issue so people can subscribe and get notified when this is being worked on.

**Comment by wilsonowilson** [comment]
Adding support for macOS would be pretty easy using NSApp. 
I've worked on a simple minimiaturization sample using my plugin [window_activator](https://github.com/wilsonowilson/window_activator). 

``` dart
 let mainWindow = NSApp.windows[0]
 mainWindow.miniaturize(self);
```

Adding in the rest of the features mentioned in the README would also be possible.

I'm willing to contribute to this repo for macOS support @bitsdojo.

**Comment by bitsdojo** [comment]
Hi @wilsonowilson!

I am currently transitioning the plugin to a federated one. I am doing this so that every platform (windows/macos/linux) will have it's own package. 

After the transition to the federated plugin is complete, it should be much easier to add macOS support and I hope you will contribute then. I will let you know once the transition is complete.

**Comment by esDotDev** [comment]
I don't think there is actually anything to be done for MacOS, it can all be done in xcode by just toggling some checkboxes :D 
https://medium.com/flutter-community/transparent-title-bar-on-macos-with-flutter-7043d44f25dc

* Open Runner
* Select Runner/Resources/MainMenu.xib
* Select the "Window" object (bottom-left)
* Check: 
  - Hide TitleBar
  - Transparent TitleBar
  - Full Size Content View
  
  
![image](https://user-images.githubusercontent.com/736973/104365907-d6983a80-54d5-11eb-8fae-1bcd0a26b075.png)

**Comment by bitsdojo** [comment]
Sure, you can do this if you only want to remove the title bar. 

Personally I would like to control the size of the area that is used to move the window, just like the MoveWindow widget currently works on Windows. Checking the boxes in the .xib doesn't enable doing that.

Moreover, I would like a unified API for window operations, that works the same across Windows, macOS and Linux.

Thank you for writing the comment as it might be useful for people that are only interested in removing the title bar.

**Comment by wilsonowilson** [comment]
@esDotDev although that is true, being able to customize the title at runtime, the menu bar, the control buttons, and the rest of the features mentioned in the README would be really nice true would be pretty nice to control on all the platforms.

**Comment by esDotDev** [comment]
Right I understand having the various API calls work would still be nice.

fwiw, you can customize everything everything visually with this technique, you can provide your own title or use the default one. The one thing it doesn't support is non-draggable areas (but that would be very non-standard on macos anyways, the entire titlebar is always draggable)

Not sure if it's useful, but most of the other API's are covered in the window_size plugin, at least sizing and positioning and setting the title, for all 3 platforms. At least there should be some code to grab :)

**Comment by bitsdojo** [comment]
Started working on macOS support in 0.0.5. 

The example application now also runs on macOS but still have some functionality to be implemented.

**Comment by bitsdojo** [comment]
macOS support has been added in https://github.com/bitsdojo/bitsdojo_window/commit/51081d7933ea4600fba8e766443559a9c36562f3
