### ISSUE TITLE
Using flutter 2.13.0.-0.1pre lib/src/window.dart is producing an error when compiling

### ISSUE THREAD

**Issue by Tanthus** [bitsdojo/bitsdojo_window#163]
This only happens in the beta channel, still compiles fine in the main one.

I get the following the error:
/C:/Dev/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_windows-0.1.0/lib/src/window.dart(72,36): error GF1577525: 'Size' is imported from both 'dart:ffi' and 'dart:ui'. [C:\proj\prolific-app-flutter\app\build\windows\flutter\flutter_assemble.vcxproj]

I will report this for flutter dart:ffi and dart:ui as well.  But you might also want to make adjustments here just in case.

**Comment by RawadZogheib** [comment]
Any solution?

**Comment by memotai-admin** [comment]
> 

Same here

**Comment by filipenanclarez** [comment]
> Any solution? Same error on the stable channel 3.0.0

Same here

**Comment by bitsdojo** [comment]
Fixed in `bitsdojo_window: ^0.1.2` - https://github.com/bitsdojo/bitsdojo_window/commit/f320b623db107b03a5976fd88e52ec4fe81fa0c9

Closing this issue. Please re-open if needed.
