### ISSUE TITLE
build failure on Windows 11

### ISSUE THREAD

**Issue by Anci3ntR0ck** [bitsdojo/bitsdojo_window#167]
`/D:/Environment/flutter/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/bitsdojo_window_windows-0.1.0/lib/src/window.dart(70,12): error G0A556F40: The return type of the method 'WinWindow.size' is 'Size/*1*/', which does not match the return type, 'Size/*2*/', of the overridden method, 'DesktopWindow.size'. [D:\Documents\Code\Java\flutter-folio\build\windows\flutter\flutter_assemble.vcxproj]
/D:/Environment/flutter/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/bitsdojo_window_windows-0.1.0/lib/src/window.dart(176,17): error G4906CC7E: The parameter 'newSize' of the method 'WinWindow.size' has type 'Size/*1*/', which does not match the corresponding type, 'Size/\*2*/', in the overridden method, 'DesktopWindow.size'. [D:\Documents\Code\Java\flutter-folio\build\windows\flutter\flutter_assemble.vcxproj]
/D:/Environment/flutter/.pub-cache/hosted/mirrors.tuna.tsinghua.edu.cn%2547dart-pub%2547/bitsdojo_window_windows-0.1.0/lib/src/window.dart(120,12): error G0A556F40: The return type of the method 'WinWindow.titleBarButtonSize' is 'Size/*1*/', which does not match the return type, 'Size/\*2*/', of the overridden method, 'DesktopWindow.titleBarButtonSize'. [D:\Documents\Code\Java\flutter-folio\build\windows\flutter\flutter_assemble.vcxproj]`
and so on
seems like conflict between two `Size`    , but I have no idea. can somebody help?

**Comment by bitsdojo** [comment]
Please try with`bitsdojo_window: ^0.1.2` - https://github.com/bitsdojo/bitsdojo_window/commit/f320b623db107b03a5976fd88e52ec4fe81fa0c9 and re-open if needed.
