### ISSUE TITLE
error: use of undeclared identifier 'bitsdojo_window_from'

### ISSUE THREAD

**Issue by tomaszdrozdz** [bitsdojo/bitsdojo_window#168]
### linux/my_application.cc  

```
// NEEDED BY bitsdojo_window.dart
auto bdw = bitsdojo_window_from(window);
bdw->setCustomFrame(true);
//gtk_window_set_default_size(window, 1280, 720);

gtk_widget_show(GTK_WIDGET(window));
```
   
### my_app.dart  
 
```
void main() {
   runApp(const MyApp());
        
   doWhenWindowReady((){
       appWindow.title = 'MyTitle'; }); }
```

### And I get  
 
> Building Linux application...
> /var/home/tomek/DartProjects/senver/linux/my_application.cc:51:14: error: use of undeclared identifier 'bitsdojo_window_from'
> Exception: Build process failed

------------------------

### *

```
$ flutter --version
```
>Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git
>Framework • revision 5464c5bac7 (3 weeks ago) • 2022-04-18 09:55:37 -0700
>Engine • revision 57d3bac3dd
>Tools • Dart 2.16.2 • DevTools 2.9.2

### *

Android Studio Bumblebee | 2021.1.1 Patch 3
Build #AI-211.7628.21.2111.8309675, built on March 16, 2022
Runtime version: 11.0.11+0-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.17.5-200.fc35.x86_64
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 4
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.github.mzdm.embedded_dartpad (0.0.4), Dart (211.7817), org.jetbrains.kotlin (211-1.6.21-release-334-AS7442.40), io.flutter (67.0.1)
Current Desktop: GNOME

### *

```
$ cat /etc/fedora-release 
```
> Fedora release 35 (Thirty Five)

**Comment by bitsdojo** [comment]
Please try updating to the latest `bitsdojo_window` version.
