### ISSUE TITLE
Could you fix your plugin to  be compatible with flutter 3.0?

### ISSUE THREAD

**Issue by YowFung** [bitsdojo/bitsdojo_window#169]
After I upgrade flutter SDK to 3.0, I can't run my app. 
Could you provide a new version to add compatibility with flutter 3.0?

Related: https://github.com/flutter/flutter/issues/103571#issuecomment-1125694094

**Comment by bitsdojo** [comment]
Fixed in `bitsdojo_window: ^0.1.2` - https://github.com/bitsdojo/bitsdojo_window/commit/f320b623db107b03a5976fd88e52ec4fe81fa0c9

Closing this issue. Please re-open if needed.
