### ISSUE TITLE
Describe difference to the official window_size plugin

### ISSUE THREAD

**Issue by cbenhagen** [bitsdojo/bitsdojo_window#17]
There is a (semi-) official plugin with very similar functionality at https://github.com/google/flutter-desktop-embedding/tree/master/plugins/window_size. It would be nice to describe what sets this plugin apart. Maybe the two could be merged?

**Comment by esDotDev** [comment]
On this topic, I recently got a pretty solid "universal" drag going, using the window_size plugin (which supports all 3 plugins out of the box). 

This is some ugly code, and it's not quite perfect, but it's really close:
```
onPointerMove: (d) async {
  if (_ignoreNext) {
    _ignoreNext = false;
    return;
  }
  _windowPos += d.delta * 2;
  Window.setWindowFrame(_windowPos & _windowSize);
  _ignoreNext = true;
},
```

Seems like there might be some opportunity to build on the base API's from WindowSize, and just add on what is really unique to this package (prefab'd Windows btns, maximize/minimize methods, and ability to hide native title bar).

**Comment by cbenhagen** [comment]
Haven't had the chance to test this on a non-retina screen but I guess you'd might want to do:
```dart
_windowPos += d.delta * MediaQuery.of(context).devicePixelRatio
```

Related issue: https://github.com/flutter/flutter/issues/71680

**Comment by geocine** [comment]
With regards to  dragging, isn't the `Move` widget enough for your use  case @esDotDev ?
