### ISSUE TITLE
Build Failed on windows 10  error GCE1592F9:

### ISSUE THREAD

**Issue by hyderali0889** [bitsdojo/bitsdojo_window#171]
error GCE1592F9: 'Size' is imported from both 'dart:ffi' and 'dart:ui'. 
When running with out the bitsdojo package app runs but when using this package this error occurs .

**Comment by asmith20002** [comment]
This happens because of Flutter 3.0. This package needs to get updated for Flutter 3.0
Judging by the last updates and number of issues/pull-requests it seems that this package is abandoned so don't get your hopes high.

**Comment by bitsdojo** [comment]
> it seems that this package is abandoned.

For everyone else reading this and wondering about it:

The package is not abandoned in any way. 

Been busy with taking care of my health as it has greatly impacted my ability to work in the last months.

I am slowly recovering so updates are coming in the near future.

**Comment by PeterNjeim** [comment]
https://github.com/flutter/flutter/issues/103571#issuecomment-1125705625:
> Looks like we added Size to dart:ffi and anyone who imports both dart:ffi and dart:ui is going to have an issue. Specifically looks like this is bitsdojo_window_windows and bitsdojo_window_linux.
>
> The solution is to say hide Size on the import 'dart:ffi' line.

**Comment by bitsdojo** [comment]
Fixed in `bitsdojo_window: ^0.1.2` - https://github.com/bitsdojo/bitsdojo_window/commit/f320b623db107b03a5976fd88e52ec4fe81fa0c9

Closing this issue. Please re-open if needed.
