### ISSUE TITLE
Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'bitsdojo_window_api': error code -2059408968

### ISSUE THREAD

**Issue by liufangzhou53** [bitsdojo/bitsdojo_window#173]
Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'bitsdojo_window_api': error code -2059408968
#1      bitsdojoWindowAPI
package:bitsdojo_window_windows/src/native_api.dart:66
#2      bitsdojoWindowAPI (package:bitsdojo_window_windows/src/native_api.dart)
package:bitsdojo_window_windows/src/native_api.dart:1
#3      _publicAPI
package:bitsdojo_window_windows/src/native_api.dart:69
#4      _publicAPI (package:bitsdojo_window_windows/src/native_api.dart)
package:bitsdojo_window_windows/src/native_api.dart:1
#5      _setWindowCanBeShown
package:bitsdojo_window_windows/src/native_api.dart:29
#6      _setWindowCanBeShown (package:bitsdojo_window_windows/src/native_api.dart)
package:bitsdojo_window_windows/src/native_api.dart:1
#7      setWindowCanBeShown
package:bitsdojo_window_windows/src/native_api.dart:30
#8      BitsdojoWindowWindows.doWhenWindowReady.<anonymous closure>
package:bitsdojo_window_windows/src/bitsdojo_window_windows_real.dart:19
#9      _rootRunUnary (dart:async/zone.dart:1434:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
<asynchronous suspension>
Connecting to VM Service at ws://127.0.0.1:49360/4RVSfkP5eNo=/ws

flutter version
Flutter 2.9.0-1.0.pre.29 • channel master • https://github.com/flutter/flutter.git
Framework • revision 6b51924de3 (5 months ago) • 2021-12-09 16:49:10 -0500
Engine • revision 2516ea636d
Tools • Dart 2.16.0 (build 2.16.0-85.0.dev) • DevTools 2.9.1

**Comment by bitsdojo** [comment]
Please try updating to the latest `bitsdojo_window` version.
