### ISSUE TITLE
Error: 'Size' is imported from both 'dart:ffi' and 'dart:ui'

### ISSUE THREAD

**Issue by wasimsafdar** [bitsdojo/bitsdojo_window#174]
I am working with a Flutter app that uses this library. I am getting this error because Size is used in both ffi and ui library. The solution I found is to hide Size from one library in windows.dart file in Windows and Linux platforms like this.

import 'dart:ffi' hide Size;

But this solution is not good, because every time we pull, same error appears. I am not used to work with open source code. Author or anyone update this on Github so that next time, I pull, I will not face this error. Thanks.

**Comment by bitsdojo** [comment]
Fixed in `bitsdojo_window: ^0.1.2` - https://github.com/bitsdojo/bitsdojo_window/commit/f320b623db107b03a5976fd88e52ec4fe81fa0c9

Closing this issue. Please re-open if needed.

**Comment by CodeDoctorDE** [comment]
🎉 🎉 🎉
