### ISSUE TITLE
App does not run after Flutter build windows

### ISSUE THREAD

**Issue by evertonfoz** [bitsdojo/bitsdojo_window#175]
When I run it in VS COde, the application works perfectly. The same occurs by executing the EXE file from the DEBUG folder. However, when flutter build windows is performed and I try to run the application in the RELEASE folder, the window appears with no content and no error.

The Right way, in debug mode
![image](https://user-images.githubusercontent.com/9963789/169522719-8214fdc8-5757-4413-ba5e-c1b9f5010e54.png)

The wrong way, in release mode
![image](https://user-images.githubusercontent.com/9963789/169522819-f8a6fdc8-27ad-4678-921e-70cbb801fee5.png)

**Comment by IhabZaidi** [comment]
i have the same issue

**Comment by bitsdojo** [comment]
Please try updating to the latest `bitsdojo_window` version.
