### ISSUE TITLE
[windows] update ffi and win32 dependencies

### ISSUE THREAD

**Issue by mattetti** [bitsdojo/bitsdojo_window#178]
The current dependency locks are on older versions of win32 (2.70 available) and ffi packages (2.0.0 available)
https://github.com/bitsdojo/bitsdojo_window/blob/master/bitsdojo_window_windows/pubspec.yaml#L16

This prevents developers from updating their own dependencies.

Thanks

**Comment by bitsdojo** [comment]
ffi now updated to 2.0.0 and win32 to 3.0.0
