### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by 865394064** [bitsdojo/bitsdojo_window#182]
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-001E08202ED9001E }
{ platform:macOS, arch:x86_64, id:00008103-001E08202ED9001E }
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FlutterAppDelegate", referenced from:
      type metadata for macdeskfac.AppDelegate in AppDelegate.o
  "_OBJC_CLASS_$_FlutterViewController", referenced from:
      objc-class-ref in MainFlutterWindow.o
  "_OBJC_METACLASS_$_FlutterAppDelegate", referenced from:
      _OBJC_METACLASS_$__TtC10macdeskfac11AppDelegate in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

run on Mac mini (M1, 2020).  
please help

**Comment by appinteractive** [comment]
On my M1, everything runs like a charm. Which version of Flutter are you using? Mine is 3.0.5

**Comment by 865394064** [comment]
> 在我的 M1 上，一切都像魅力一样运行。你使用的是哪个版本的 Flutter？我的是 3.0.5
Flutter 3.1.0 • channel beta • https://github.com/flutter/flutter.git

**Comment by 865394064** [comment]
> On my M1, everything runs like a charm. Which version of Flutter are you using? Mine is 3.0.5

Flutter 3.1.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision bcea432bce (3 months ago) • 2022-05-26 09:05:34 -0700

**Comment by Ahmadre** [comment]
remove your macos folder and let Flutter 3.3.8 re-create it. This Solved it for me.

**Comment by bitsdojo** [comment]
Please try updating to the latest `bitsdojo_window` version.
