### ISSUE TITLE
example is not work

### ISSUE THREAD

**Issue by luo10** [bitsdojo/bitsdojo_window#183]
<img width="712" alt="image" src="https://user-images.githubusercontent.com/17287671/174589178-fc9163ea-c34a-4ea1-8b08-d26d93fb1b54.png">
this does not work as in the example, the button in the top left corner is not hidden...

**Comment by mathewthe2** [comment]
Same problem using m1 using only the BDW_CUSTOM_FRAME flag.

When I add the BDW_HIDE_ON_STARTUP flag, however, nothing shows up and if I try to click the app from the dock the console says **Lost connection to device**.

**Comment by appinteractive** [comment]
There is a Pull-Request #184

@bitsdojo may that fix the problem?

@luo10 @mathewthe2 I use that package in combination with https://pub.dev/packages/flutter_acrylic and there is a method `Window.hideWindowControls();` that does exactly that, maybe you can try that for now!?

**Comment by maxd** [comment]
I see [such code](https://github.com/bitsdojo/bitsdojo_window/blob/9b83939c321caa438da4be598f527f028e0efa5f/bitsdojo_window/lib/src/widgets/window_button.dart#L94-L97) that hide custom buttons for macOS. 

@bitsdojo So, this issue isn't a bug, right?

**Comment by Juliotati** [comment]
@maxd  There's no bug. The window control buttons on macOS are "not supposed to be touched", unless you have a reason to. Either we should them as they are to stay uniform to the platform specific.
