### ISSUE TITLE
Shadow / Aliasing on WindowsButtons

### ISSUE THREAD

**Issue by esDotDev** [bitsdojo/bitsdojo_window#20]
I'm seeing a subtle but annoying shadow on the buttons that come in the package.

Here you can see the maximize btn, beside a regular flutter box border, and the border is quite a bit more crisp:
![image](https://user-images.githubusercontent.com/736973/104423936-f19d9580-553b-11eb-83df-40d207e3ab2c.png)

```
MaximizeWindowButton(
     colors: WindowButtonColors(iconNormal: Colors.black),
),
Container(width: 10, height: 10, decoration: BoxDecoration(border: Border.all(color: Colors.black))),
```

Quite easy to fix ourselves, but thought you might want to track it.

[Edit] Magnified in photoshop: 
![image](https://user-images.githubusercontent.com/736973/104424712-fc0c5f00-553c-11eb-8361-8d4666e30868.png)

**Comment by bitsdojo** [comment]
The buttons that come in the package use flutter_svg to render the SVG for each of the icons.

This could be fixed by modifying the SVGs or by transitioning the buttons to using simple Flutter shapes.

Open to any PR using those two methods mentioned above.

**Comment by esDotDev** [comment]
On it!

**Comment by bitsdojo** [comment]
Fixed by https://github.com/bitsdojo/bitsdojo_window/commit/814ac4ed811f4398a9cebd771f4767f63034fd63
