### ISSUE TITLE
BDW not working on Windows 22H2 22622.440

### ISSUE THREAD

**Issue by Jamminroot** [bitsdojo/bitsdojo_window#203]
Hello!
Noticed that my app stopped launching after recent update I made.

Enabling latest version of the library in `main.cpp` causes troubles with launching the application. Running in debug mode gives this (`flutter run --debug --verbose`):

```console
[+12094 ms] Error waiting for a debug connection: The log reader stopped unexpectedly, or never started.
[   +1 ms] Error launching application on Windows.
```
While disabling it seem to be "fixing" the problem (but, ofcourse, no visual sugar here).

Flutter doctor info:
```
[√] Flutter (Channel stable, 3.3.3, on Microsoft Windows [Version 10.0.22622.440], locale ru-RU)
    • Flutter version 3.3.3 on channel stable at C:\DEV\flutter_sdk

<...>

[√] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.3
    • Flutter plugin version 70.2.3
    • Dart plugin version 213.7433

[√] VS Code (version 1.71.2)
    • VS Code at C:\Users\jamminroot\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.48.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22622.440]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category. // <-Android, so N/A here
```

**Comment by bitsdojo** [comment]
What flags are enabled in main.cpp?

Does it make any difference if you remove the `BDW_HIDE_ON_STARTUP` flag?

**Comment by Jamminroot** [comment]
I'm closing the issue.

Double-checked what I have cached and what I have in a fork, it seems to be something along the lines of:

https://github.com/bitsdojo/bitsdojo_window/pull/134/files

https://github.com/bitsdojo/bitsdojo_window/issues/157#issuecomment-1169946125

Long words short: `dart cache clean` + `flutter clean` + version upgrades and resolving dependencies conflicts did the trick for me.
