### ISSUE TITLE
Problem After Update To Flutter 3.3.3

### ISSUE THREAD

**Issue by Embact** [bitsdojo/bitsdojo_window#204]
After Updating my flutter to _version_ **3.3.3**
i got some problems in this package 
When **Run**
![image](https://user-images.githubusercontent.com/54289217/194714717-3e02e226-1146-41d2-a667-6cb7387d3543.png)
![image](https://user-images.githubusercontent.com/54289217/194714752-d02e2be5-84d0-476e-86ff-6f4aa89516ea.png)
![image](https://user-images.githubusercontent.com/54289217/194714768-8b432d8f-7c74-4d97-87b1-24e39884064f.png)
![image](https://user-images.githubusercontent.com/54289217/194714771-3cbeeab8-43d0-4380-9ded-a00d358c1c63.png)

Flutter doctor -v
![image](https://user-images.githubusercontent.com/54289217/194714836-f7e37e4d-544d-49be-98bd-ad686f283bf2.png)
![image](https://user-images.githubusercontent.com/54289217/194714844-39547c19-f142-461e-8fe6-3e35aaf2aed6.png)

**Comment by jankratochvilcz** [comment]
What version did you upgrade from? Having a similar issue on a new machine; the workaround is probably to downgrade for now. Also, did you upgrade to the latest version of the package?

**Comment by Embact** [comment]
> What version did you upgrade from? Having a similar issue on a new machine; the workaround is probably to downgrade for now. Also, did you upgrade to the latest version of the package?

Actually not remember the version i upgraded from 
![image](https://user-images.githubusercontent.com/54289217/194788754-45a4b990-597a-43ce-97fa-1b24f6bca37d.png)
tried alot of versions and the latest version depend on [win32: ^3.0.0]
and [dart_console] depend on [win32: ^2.6.1] 
this package make conflict for each other

**Comment by Embact** [comment]
> What version did you upgrade from? Having a similar issue on a new machine; the workaround is probably to downgrade for now. Also, did you upgrade to the latest version of the package?

Actually not remember the version i upgraded from
![image](https://user-images.githubusercontent.com/54289217/194788929-6819b6c2-ca2d-4e70-9d84-545a8ef0fe46.png)
tried alot of versions and the latest version depend on [win32: ^3.0.0]
and [dart_console] depend on [win32: ^2.6.1]
this package make conflict for each other

**Comment by bitsdojo** [comment]
Please try updating to the latest `bitsdojo_window` version.
