### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by shema-ryan** [bitsdojo/bitsdojo_window#207]
The app have been running smoothly in the development mode but when i build  a release version , it only works on my computer but doesn't run on other windows  machines... 
i tried couple of methods , but all would suggest the missing files which was already added...
i decided to remove bitsdojo package and now it's working ....

Have build release for before and after removal of the  package. i can email or attach it for more details
beside Kuddos for such an awesome package  , it brings a lot of impossibilities to life.

**Comment by bitsdojo** [comment]
Please try updating to the latest `bitsdojo_window` version.
