### ISSUE TITLE
Add Implicit Animation for Smoother Color Fade

### ISSUE THREAD

**Issue by EriKWDev** [bitsdojo/bitsdojo_window#21]
A lot of apps (chrome in example gif below) have a tiny sleek animation to switch the color when hovering on the buttons.

![buttons](https://user-images.githubusercontent.com/19771356/104740069-c8e9eb80-5747-11eb-93c6-6d0ef5867a1e.gif)
Upper: Chrome with animations
Lower: bitsdojo_window Example

This could probably be implemented by changing the final `Container` into an `AnimatedContainer` for the WindowButtons:
```dart
AnimatedContainer(
   curve: Curves.easeInOut,
   duration: Duration(milliseconds: 120),
   color: backgroundColor
)
```

I tried to implement this for a PR, but due to how the WindowButton code was structured the WindowButtonContext was recreated every single time the build() was called inside WindowButton.
Perhaps it could be made into a StatefulWidget and we could then only switch the backgroundColor once the MouseState changes and not all the time..?

**Comment by esDotDev** [comment]
As far as I can tell, it actually only fades on mouse-out, do you see that as well?

**Comment by esDotDev** [comment]
Btw, turns out the issue was just that AnimatedContainer just can't tween from `null`, a simple `color: buttonContext.backgroundColor ?? Color(0x0),` seems to be all we need here.

**Comment by esDotDev** [comment]
PR submitted: 
https://github.com/bitsdojo/bitsdojo_window/pull/23

**Comment by EriKWDev** [comment]
> As far as I can tell, it actually only fades on mouse-out, do you see that as well? 

It's really hard to see. It might be a super quick fade-in, but the fade out is more prominent yes.

**Comment by bitsdojo** [comment]
Fixed by https://github.com/bitsdojo/bitsdojo_window/commit/1363fdde3029f9b8b844c02f4ed625ebba449635
