### ISSUE TITLE
Can I use those buttons with my own icon or define my own buttons?

### ISSUE THREAD

**Issue by Satoing** [bitsdojo/bitsdojo_window#211]
For example, I want to replace
![image](https://user-images.githubusercontent.com/68995451/211765605-20e9b82f-3367-41f4-ac67-fd958e6dea56.png)
with
![image](https://user-images.githubusercontent.com/68995451/211765789-327744fc-6191-4f80-972d-725946e64c31.png)
It's better if I can define my own buttons in the top:
![image](https://user-images.githubusercontent.com/68995451/211766363-24459118-6200-4720-b244-2a1d363145b4.png)

**Comment by nice2cu1** [comment]
@Satoing 
You can use any button, just add appWindow.minimize() or appWindow.maximizeOrRestore() or appWindow.close() in onPressed()

For example:
```
 ElevatedButton(
          onPressed: () => appWindow. minimize(),
          child: const Icon(Icons. minimize, color: Colors. black, size: 20)
        ),
```

**Comment by Satoing** [comment]
> @Satoing You can use any button, just add appWindow.minimize() or appWindow.maximizeOrRestore() or appWindow.close() in onPressed()
> 
> For example:
> 
> ```
>  ElevatedButton(
>           onPressed: () => appWindow. minimize(),
>           child: const Icon(Icons. minimize, color: Colors. black, size: 20)
>         ),
> ```

Thank you, I did it in this way.
