### ISSUE TITLE
Please support win32^5.0.0

### ISSUE THREAD

**Issue by ruolunhui** [bitsdojo/bitsdojo_window#220]
Because bitsdojo_window >=0.1.5 depends on bitsdojo_window_windows ^0.1.5 which depends on win32 ^3.0.0, bitsdojo_window >=0.1.5 requires win32 ^3.0.0.
So, because creative_production_desktop depends on both bitsdojo_window ^0.1.5 and win32 ^5.0.3, version solving failed.

**Comment by Pololot64** [comment]
This is true

**Comment by cliftonlabrum** [comment]
Same issue is happening with `share_plus` version `7.0.1`.

**Comment by Pololot64** [comment]
You can always fork and make the change yourself while waiting for the update. Then you can install the dependency using git in pubspec.yaml.

**Comment by hurelhuyag** [comment]
This issue blocked me. Because `file_picker 5.3.2 depends on win32 ^5.0.2`

**Comment by SteZhyv** [comment]
> You can always fork and make the change yourself while waiting for the update. Then you can install the dependency using git in pubspec.yaml.

Can you explain how to do it?

**Comment by byunggilchoi** [comment]
> > You can always fork and make the change yourself while waiting for the update. Then you can install the dependency using git in pubspec.yaml.
> 
> Can you explain how to do it?

Below is the guide from Flutter official site.
https://docs.flutter.dev/packages-and-plugins/using-packages#dependencies-on-unpublished-packages

**Comment by bitsdojo** [comment]
I will push a new version soon so that this won't be neeeded.

Just need to find some time for it.

Will reply here once I  push the update.

Bit

**Comment by JHenneberg** [comment]
> I will push a new version soon so that this won't be neeeded.
> 
> Just need to find some time for it.
> 
> Will reply here once I push the update.
> 
> Bit

I just glanced at #216 , which looks like it is solving a lot of issues. Just needs a little version bumb from `5.0.0.` to `5.0.5`

**Comment by hsangtini** [comment]
Or using overrides on pubspec.yaml:

```
dependency_overrides:
  win32: ^5.0.5
```

**Comment by Juliotati** [comment]
> I will push a new version soon so that this won't be neeeded.
> 
> Just need to find some time for it.
> 
> Will reply here once I push the update.
> 
> Bit

Much appreciated @bitsdojo

**Comment by darkomenx** [comment]
Again the package install "super_drag_and_drop" is forbidden due to lower requirements on win32.

 Use BitsDojo in your project become very discouraged due that :( 

@bitsdojo all the community needs you !

**Comment by bitsdojo** [comment]
Thank you for the heads-up!

Just need to finish something on macOS and I will get back with a new version.

Thank you for your patience.

**Comment by bitsdojo** [comment]
Please try updating to the latest `bitsdojo_window` version.

**Comment by darkomenx** [comment]
Hi @bitsdojo

I confirm that I upgrade bitsdojo_window package to 0.1.6 version AND disabled dependency_overrides win32: 5.1.1.
I also confirm that my application run correctly after that.

Lot of thanks for your package, your work and reactivity for fix issue. 👍
