### ISSUE TITLE
please upgrade

### ISSUE THREAD

**Issue by Islam-Darwish** [bitsdojo/bitsdojo_window#223]
file_picker >=5.3.2 depends on win32 ^5.0.2 and file_picker >=5.2.11 <5.3.2 depends on win32 ^4.1.3, file_picker >=5.2.11 requires win32 ^4.1.3 or ^5.0.2.

**Comment by JHenneberg** [comment]
It is solved in #216 but not merged yet.

**Comment by bitsdojo** [comment]
Please try updating to the latest `bitsdojo_window` version.
