### ISSUE TITLE
Doesn't work in Windows 11

### ISSUE THREAD

**Issue by PMack101** [bitsdojo/bitsdojo_window#229]
In the build release my project won't run in Windows 11. Commenting out the bitsdojo_window lines added in main.cpp to disable bitsdojo enables the app to run on Windows 11, but without bitsdojo...

**Comment by cliftonlabrum** [comment]
It's working for me in Windows 11. Can you share your `main.cpp` code?

**Comment by bitsdojo** [comment]
> In the build release my project won't run in Windows 11. Commenting out the bitsdojo_window lines added in main.cpp to disable bitsdojo enables the app to run on Windows 11, but without bitsdojo...

Hi there,

Do you have more details on this? What is the current behavior you are experiencing?

**Comment by bitsdojo** [comment]
Please try updating to the latest `bitsdojo_window` version.
