### ISSUE TITLE
Can Someone Fork this Repo and Take Over?

### ISSUE THREAD

**Issue by cliftonlabrum** [bitsdojo/bitsdojo_window#232]
It seems the owner of this repo is unavailable. Is there someone that can fork this and keep it going? We could all start using a forked version of this package (perhaps with a new name to avoid confusion).

I would do it myself, but I know next to nothing about C++. 😅

**Comment by bitsdojo** [comment]
Thank you for your comment.

I am still monitoring the issues and will release a new version as soon as I can.

**Comment by cliftonlabrum** [comment]
@bitsdojo Can you please merge this PR then? https://github.com/bitsdojo/bitsdojo_window/pull/216

This package is preventing me from updating a variety of other ones. 😊

**Comment by bitsdojo** [comment]
> @bitsdojo Can you please merge this PR then? https://github.com/bitsdojo/bitsdojo_window/pull/216
> 
> 
> 
> This package is preventing me from updating a variety of other ones. 😊

Sure, it's on my list.

**Comment by Juliotati** [comment]
# nice, THANKS!! @bitsdojo
