### ISSUE TITLE
There were someone published v3, is this your work?

### ISSUE THREAD

**Issue by lucasjinreal** [bitsdojo/bitsdojo_window#235]
Your work probably stolen by others... Please upgrade this lib, too many dependencies are outdated

**Comment by bitsdojo** [comment]
Hi @lucasjinreal 

No, that is not my work, they are just using the name without my consent.

I am currently working on the new version which will come out soon.

**Comment by lucasjinreal** [comment]
@bitsdojo thank u so much!

I am sorry I posted in your issue to suggest this fork, it was not work on macOS..... they renamed your lib but pod install can not even be run.

I am hoping you get it work and update again, thank u so much for the work.

Meanwhile, my fork just work out of box at the moment, the main issue could be win32 dependencies constraint too low.

**Comment by bitsdojo** [comment]
Please try updating to the latest version.
