### ISSUE TITLE
dependencies issue when upgrading file_picker package

### ISSUE THREAD

**Issue by dinesh-hannurkar** [bitsdojo/bitsdojo_window#237]
Resolving dependencies...
Because bitsdojo_window_windows 0.1.5 depends on win32 ^3.0.0 and no versions of bitsdojo_window_windows match >0.1.5 <0.2.0, bitsdojo_window_windows ^0.1.5 requires win32 ^3.0.0.
And because file_picker >=5.3.2 depends on win32 ^5.0.2, file_picker >=5.3.2 is incompatible with bitsdojo_window_windows ^0.1.5.
And because bitsdojo_window 0.1.5 depends on bitsdojo_window_windows ^0.1.5 and no versions of bitsdojo_window match >0.1.5 <0.2.0, file_picker >=5.3.2 is incompatible with bitsdojo_window ^0.1.5

**Comment by alaaelbarasi** [comment]
I have the same issue regarding bitsdojo_window dependency, Is there any progress?

**Comment by jtrepagne** [comment]
Same problem here trying to use bitsdojo_window alongside flutter_quill. I got flutter_quill 6.4.4 but i need the LTS 8.6.1.
Here's my log :
```
Because flutter_quill >=7.4.12 depends on device_info_plus ^9.1.0 which depends on win32 >=4.0.0 <6.0.0, flutter_quill >=7.4.12 requires win32 >=4.0.0 <6.0.0.
And because bitsdojo_window_windows 0.1.5 depends on win32 ^3.0.0 and no versions of bitsdojo_window_windows match >0.1.5 <0.2.0, flutter_quill >=7.4.12 is incompatible with bitsdojo_window_windows ^0.1.5.
And because bitsdojo_window 0.1.5 depends on bitsdojo_window_windows ^0.1.5 and no versions of bitsdojo_window match >0.1.5 <0.2.0, flutter_quill >=7.4.12 is incompatible with bitsdojo_window ^0.1.5.
So, because my_flutter_project depends on both bitsdojo_window ^0.1.5 and flutter_quill ^8.6.1, version solving failed.
```
Any dependency upgrade planned ? Thanks a lot.

**Comment by darkomenx** [comment]
The package requirement win32 : 3.0.0 only 
but dart/win32 is now at : 5.1.1

The real question is : This package can be compatible with latest win32 package without any change or not ?

If no, what issue have you facing for provide compatible package ?

**Comment by bitsdojo** [comment]
Please try updating to the latest `bitsdojo_window` version.

**Comment by darkomenx** [comment]
Hi @bitsdojo 

I confirm that I upgrade bitsdojo_window package to 0.1.6 version AND disabled dependency_overrides win32: 5.1.1.
I also confirm that my application run correctly after that.

Lot of thanks for your package, your work and reactivity for fix issue. 👍
