### ISSUE TITLE
doWhenWindowReady never called on macOS Sonoma

### ISSUE THREAD

**Issue by bobmoff** [bitsdojo/bitsdojo_window#238]
Created a new flutter project for platform macos and added bitsdojo_window plugin.
Followed instructions in README. 

When running till app the windows is never shown. I added debugprint inside doWhenWindowReady and it is never printed.

Apple M1 Max, macOS Sonoma 14.1.1 (23B81)

**Comment by jctaoo** [comment]
same error, only occurs on flutter 3.16.x, 3.13.x works

**Comment by jctaoo** [comment]
It seems that as BitsdojoWindow was set to inVisible by default, waitUntilFirstFrameRasterized won't get completed until window show.

If you click your app icon on the dock, then click any one of menu item like `Edit` or `View`, doWhenWindowReady should be called

**Comment by bitsdojo** [comment]
Try this as a temporary solution:

```dart
void main() {
  appWindow.size = const Size(600, 450);
  runApp(const MyApp());
  appWindow.show();
  doWhenWindowReady(() {
   ...
```
Also make sure to update to the latest `bitsdojo_window` version.
