### ISSUE TITLE
Cmake Error: No target

### ISSUE THREAD

**Issue by mmosir** [bitsdojo/bitsdojo_window#239]
when I run the project，I got the error：
_No target "bitsdojo_window_windows_v3_plugin"_

**Comment by jctaoo** [comment]
You should run `bitsdojo_window/example` for test, this repo has a series dart package for different platforms but the primary package is located at bisdojo_window.

- `cd bitsdojo_window/example`
- `flutter run -d <your_platform>`

**Comment by bitsdojo** [comment]
Please try the latest bitsdojo_window version.
