### ISSUE TITLE
`doWhenReady()` not doing when ready

### ISSUE THREAD

**Issue by Wind-Explorer** [bitsdojo/bitsdojo_window#244]
Specifications:
* macOS Sonoma 14.2.1
* Flutter 3.16.3 on darwin-arm64
* `bitsdojo_window: ^0.1.6`

<hr>

The `doWhenReady()` function doesn't seem to know exactly when the window is ready, or that the factor it uses to decide when the window is ready is off.

The function is only executed when a menu entry in the menu bar is opened.

Here's a short video demonstration to illustrate the issue

https://github.com/bitsdojo/bitsdojo_window/assets/66894537/c8f69500-29a3-4594-9bff-a8ff20d26563

Any advice to resolve this issue would be appreciated, thank you.

<hr>

Below is my Flutter code for the setup in the video:

```dart
import 'package:bitsdojo_window/bitsdojo_window.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
  doWhenWindowReady(() {
    print("ready!");
    initializeWindow();
  });
}

void initializeWindow() {
  var windowInstance = appWindow;
  windowInstance.minSize = const Size(780, 550);
  windowInstance.size = const Size(1000, 800);
  windowInstance.alignment = Alignment.center;
  windowInstance.title = 'My App';
  windowInstance.show();
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: const Placeholder(),
    );
  }
}
```

I'm almost confident that the code in `MainFlutterWindow.swift` is fine as it is copied straight from the documentation. here it is in case helpful.
```swift
import Cocoa
import FlutterMacOS
import bitsdojo_window_macos

class MainFlutterWindow: BitsdojoWindow {
  override func bitsdojo_window_configure() -> UInt {
    return BDW_CUSTOM_FRAME | BDW_HIDE_ON_STARTUP
  }

  override func awakeFromNib() {
    let flutterViewController = FlutterViewController()
    let windowFrame = self.frame
    self.contentViewController = flutterViewController
    self.setFrame(windowFrame, display: true)

    RegisterGeneratedPlugins(registry: flutterViewController)

    super.awakeFromNib()
  }
}
```

**Comment by bitsdojo** [comment]
Looks like there are some recent changes in the Flutter framework window lifecycle that I need to take care of.

Does this work as a temporary solution?

https://github.com/bitsdojo/bitsdojo_window/issues/238#issuecomment-1868308533

**Comment by Wind-Explorer** [comment]
I see, it is an existing known issue. Thanks for the solution, as of now on my side things are working as expected. Will close the issue.
