### ISSUE TITLE
app not responded with new Channel master, 1.26.0-13.0.pre.122

### ISSUE THREAD

**Issue by salahturkmen** [bitsdojo/bitsdojo_window#25]
Flutter (Channel master, 1.26.0-13.0.pre.122, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
    • Flutter version 1.26.0-13.0.pre.122 at C:\flutter
    • Framework revision e599cdd414 (4 hours ago), 2021-01-22 11:07:08 -0800
    • Engine revision 90641fa923
    • Dart version 2.12.0 (build 2.12.0-248.0.dev)

**Comment by SahajRana** [comment]
It's happening for my app as well. I believe it's with the latest flutter update.

**Comment by bitsdojo** [comment]
Thank you for reporting! Will investigate.

**Comment by bitsdojo** [comment]
This is related to the latest Flutter update. Unfortunately there isn't much I can do from my side and this affects other packages as well. 

I would recommend using `1.26.0-12.0.pre` until then. I will close this for now.

**Comment by bitsdojo** [comment]
Fixed by https://github.com/bitsdojo/bitsdojo_window/commit/814ac4ed811f4398a9cebd771f4767f63034fd63
