### ISSUE TITLE
null-safety support!

### ISSUE THREAD

**Issue by Ali-Fadaei** [bitsdojo/bitsdojo_window#33]
with flutter v2.0.0, Dart's sound null-safety is stable now, so for safe migrate projects to it, flutter recommended wait for migration of all project dependencies to null-safety, I have project depended on this awesome flutter plugin, please migrate it 🙏🏻

**Comment by DeepStyles** [comment]
me too...

**Comment by MBeliou** [comment]
You can work around this issue by running your app using the **--no-sound-null-safety** argument.

**Comment by Ali-Fadaei** [comment]
@MBeliou I know but mixed-version programs don’t get all the advantages that null safety can bring.
https://dart.dev/null-safety/unsound-null-safety

**Comment by geocine** [comment]
This is a duplicate issue of #29

**Comment by bitsdojo** [comment]
Closing this as a duplicate. Check https://github.com/bitsdojo/bitsdojo_window/issues/29 for updates.
