### ISSUE TITLE
Dependency Conflict with Device_info_plus

### ISSUE THREAD

**Issue by Ali-Fadaei** [bitsdojo/bitsdojo_window#34]
Because device_info_plus >=1.0.0 depends on device_info_plus_platform_interface ^1.0.0 which depends on plugin_platform_interface ^2.0.0, device_info_plus >=1.0.0 requires plugin_platform_interface ^2.0.0.

And because bitsdojo_window_platform_interface 0.0.2 depends on plugin_platform_interface ^1.0.1 and no versions of bitsdojo_window_platform_interface match >0.0.2 <0.1.0, device_info_plus >=1.0.0 is incompatible with bitsdojo_window_platform_interface ^0.0.2.

And because bitsdojo_window 0.0.8 depends on bitsdojo_window_platform_interface ^0.0.2 and no versions of bitsdojo_window match >0.0.8 <0.1.0, device_info_plus >=1.0.0 is incompatible with bitsdojo_window ^0.0.8.

So, because DigiHaseb depends on both bitsdojo_window ^0.0.8 and device_info_plus ^1.0.0, version solving failed.
pub get failed (1; So, because DigiHaseb depends on both bitsdojo_window ^0.0.8 and device_info_plus ^1.0.0, version solving failed.)
exit code 1

**Comment by SahajRana** [comment]
I have received the same error.
```
Because no versions of file_selector_platform_interface match >2.0.2 <3.0.0 and file_selector_platform_interface 2.0.2 depends on plugin_platform_interface ^2.0.0, file_selector_platform_interface ^2.0.2 requires plugin_platform_interface ^2.0.0.
And because bitsdojo_window >=0.0.7 depends on bitsdojo_window_platform_interface ^0.0.2 which depends on plugin_platform_interface ^1.0.1, file_selector_platform_interface ^2.0.2 is incompatible with bitsdojo_window >=0.0.7.
So, because ide depends on both bitsdojo_window ^0.0.9 and file_selector_platform_interface ^2.0.2, version solving failed.
pub get failed (1; So, because ide depends on both bitsdojo_window ^0.0.9 and file_selector_platform_interface ^2.0.2, version solving failed.)

```

**Comment by bitsdojo** [comment]
Should be fixed by https://github.com/bitsdojo/bitsdojo_window/commit/3fd4412c7b071e257b3ff33c863438ad358049ab
