### ISSUE TITLE
Expose setter for titleBarHeight 

### ISSUE THREAD

**Issue by geocine** [bitsdojo/bitsdojo_window#37]
Expose setter for `titleBarHeight` so we can have thick title bars like Chrome

![Screenshot 2021-03-07 at 8 26 57 PM](https://user-images.githubusercontent.com/507464/110239762-97411400-7f83-11eb-8207-aead7345cdc7.png)

**Comment by bitsdojo** [comment]
What are you trying to achieve?

**Comment by geocine** [comment]
I want to set the size of the `titleBarHeight` so that the window has a large area where I can drag and move it , At the same time I can add larger widgets inside that titlebar similar to the tabs on a browser like Chrome.

**Comment by bitsdojo** [comment]
You can place a `MoveWindow` widget inside any widget you want to use for moving the window.

For the title bar can use a `SizedBox` widget with a child `MoveWindow` widget inside like this:

```dart
        SizedBox(
          height: 40, // set your title bar height here
          child: MoveWindow(
            child: Container(
              color: Colors.yellow[700], // set your title bar color here
              child: .. // put anything inside this Container
            ), // Container
          ), // MoveWindow
        ), // SizedBox
```
