### ISSUE TITLE
Window Jitter during resize on Windows 10

### ISSUE THREAD

**Issue by geocine** [bitsdojo/bitsdojo_window#39]
Elements are jittering when resizing the window on Window 10

![jitter](https://user-images.githubusercontent.com/507464/110278890-1a5d7b00-8013-11eb-9030-2b5fac78c519.gif)

This GIF does not represent it accurately, but you can produce it by rapidly resizing the window

**Comment by geocine** [comment]
Ok , just want you to know @bitsdojo , this does not happen on the flutter demo app, only when I added this plugin

**Comment by bitsdojo** [comment]
What is the Flutter version and Flutter channel that you are using?

**Comment by geocine** [comment]
@bitsdojo  I upgraded to latest stable here is my flutter now , that jittering content is now gone, however I now see a somehow related issue. If you do this quickly, you will see the issue. Note that I do not see this happen on the flutter demo application.

![jitter2](https://user-images.githubusercontent.com/507464/110790253-cc16d900-82ab-11eb-9ab2-c9ada17991fc.gif)

You will notice it , this is one frame.

![B](https://user-images.githubusercontent.com/507464/110790319-df29a900-82ab-11eb-9965-6edbdd35ede7.PNG)

**Comment by geocine** [comment]
@bitsdojo  Here is a minimum reproduction of the issue

https://github.com/geocine/flutter-jitter-issue

**main** - Flutter demo, simple Hello World
**issue/jitter** - Added bitsdojo_window

Run with 
```
flutter run -d windows --no-sound-null-safety
```

**Comment by bitsdojo** [comment]
How do other apps with non-standard title bar behave on the machine where you're testing this?

**Comment by bitsdojo** [comment]
Should be fixed by https://github.com/bitsdojo/bitsdojo_window/commit/3fd4412c7b071e257b3ff33c863438ad358049ab
