### ISSUE TITLE
Dragging window from maximized state title bar rendering issue

### ISSUE THREAD

**Issue by geocine** [bitsdojo/bitsdojo_window#41]
```
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Version 10.0.19041.331], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.1)
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.54.1)
[√] Connected device (2 available)
```
You have to grab it from the outer edge while it is maximized 
![draggingfrommax2](https://user-images.githubusercontent.com/507464/110897126-da123b80-8337-11eb-84aa-df97586aa10b.gif)

Here is a frame from the GIF above
![draggingfrommax](https://user-images.githubusercontent.com/507464/110897272-1cd41380-8338-11eb-8f86-99928f745ebb.PNG)

Here is a minimum reproduction of the issue

https://github.com/geocine/flutter-jitter-issue

main - Flutter demo, simple Hello World
issue/jitter - Added bitsdojo_window

**Comment by bitsdojo** [comment]
Should be fixed by https://github.com/bitsdojo/bitsdojo_window/commit/3fd4412c7b071e257b3ff33c863438ad358049ab
