### ISSUE TITLE
Linux usage

### ISSUE THREAD

**Issue by rickbsgu** [bitsdojo/bitsdojo_window#43]
Please add a section in the readme for linux - particularly what needs to be modified and where in the c++ files.

Thanks

**Comment by bitsdojo** [comment]
Hi there! 

Linux support is not finished yet but I will add instructions once it is ready.

**Comment by debonzi** [comment]
Hi,
I didn't test it  a lot but it seems that with only this simple change the example is running just fine in Ubuntu Linux 18.04

```
diff --git a/linux/my_application.cc b/linux/my_application.cc
index d0094bc..e7df1dc 100644
--- a/linux/my_application.cc
+++ b/linux/my_application.cc
@@ -61,6 +61,9 @@ static void my_application_activate(GApplication* application) {
   fl_register_plugins(FL_PLUGIN_REGISTRY(view));
 
   gtk_widget_grab_focus(GTK_WIDGET(view));
+
+  // Window Bar will be handled by bitsdojo_window
+  gtk_window_set_decorated(window, FALSE);
 }
 
 // Implements GApplication::local_command_line.
```

I hope it helps.

**Comment by mneilly** [comment]
Thanks for your efforts!

Since you said you're still working on Linux support you may already be aware of these issues but in case you aren't...

Following the tut from the video (https://youtu.be/bee2AHQpGK4) and making the change suggested by @debonzi generally worked for me but...

If I click the minimize button first the window either hangs or crashes with:

> Launching lib/main.dart on Linux in debug mode...
> Building Linux application...
> Debug service listening on ws://127.0.0.1:45103/4guDepD3iG0=/ws
> Syncing files to device Linux...
> [xcb] Unknown sequence number while processing reply
> [xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
> [xcb] Aborting, sorry about that.
> try_bitsdojo_window: ../../src/xcb_io.c:643: _XReply: Assertion `!xcb_xlib_threads_sequence_lost' failed.
> Lost connection to device.

If I first click maximize, minimize seems to work fine after that point.

Also, I can click to move the window but only every other click works. Click move. Click no mode. Click move. Click no move and so on.

https://user-images.githubusercontent.com/5897087/115134840-82b35b00-9fc8-11eb-9c02-61558699798d.mp4

**Comment by tomassasovsky** [comment]
Hi! I'm getting pretty much the same error:

```
Launching lib/main.dart on Linux in debug mode...
lib/main.dart:1
Connecting to VM Service at ws://127.0.0.1:39025/c-3J3cL4VPA=/ws
(example:49968): Gdk-CRITICAL **: 11:25:53.580: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed
(example:49968): Gdk-CRITICAL **: 11:25:53.581: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
example: ../../src/xcb_io.c:269: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Lost connection to device.
Exited (sigterm)
```

I'm running the example code on Ubuntu 21.04 with GNOME 40.

**Comment by bitsdojo** [comment]
Thanks everyone for your comments. Planned to push out a new version with improved Linux support today but had to visit the hospital instead.

Fortunately the doctors have a fix for me and although I can't type at full speed due to a hand injury, I will do my best to release the new version soon.

**Comment by blemelin** [comment]
> Also, I can click to move the window but only every other click works. Click move. Click no mode. Click move. Click no move and so on.

I might not be an expert, but it might be related to this other issue : https://github.com/flutter/flutter/issues/74939

See this method and the call to `gtk_window_begin_move_drag` at line 55 : 
https://github.com/bitsdojo/bitsdojo_window/blob/f2d8dfabec25722526c8996929086902df5e8fbb/bitsdojo_window_linux/linux/bitsdojo_window_plugin.cpp#L47-L66

**Comment by kartikeyshaurya** [comment]
did anybody got the support for linux

**Comment by bitsdojo** [comment]
An update is coming tomorrow. Stay tuned.

**Comment by kartikeyshaurya** [comment]
>  gtk_window_set_decorated(window, FALSE);



> Hi,
> I didn't test it a lot but it seems that with only this simple change the example is running just fine in Ubuntu Linux 18.04
> 
> ```
> diff --git a/linux/my_application.cc b/linux/my_application.cc
> index d0094bc..e7df1dc 100644
> --- a/linux/my_application.cc
> +++ b/linux/my_application.cc
> @@ -61,6 +61,9 @@ static void my_application_activate(GApplication* application) {
>    fl_register_plugins(FL_PLUGIN_REGISTRY(view));
>  
>    gtk_widget_grab_focus(GTK_WIDGET(view));
> +
> +  // Window Bar will be handled by bitsdojo_window
> +  gtk_window_set_decorated(window, FALSE);
>  }
>  
>  // Implements GApplication::local_command_line.
> ```

it worked thanks for posting here man @debonzi

**Comment by renejk** [comment]
no instructions to use on linux yet?

**Comment by bitsdojo** [comment]
> no instructions to use on linux yet?

Just pushed a new version with improved Linux support. Please test it and report any issues you encounter.

Also added basic instructions for Linux here: https://github.com/bitsdojo/bitsdojo_window#for-linux-apps

**Comment by bitsdojo** [comment]
As Linux instructions are now available in `README.MD` I will close this.

Feel free to open other issues if you encounter any problems with the Linux package.
