### ISSUE TITLE
pls update depandency

### ISSUE THREAD

**Issue by pepezoro** [bitsdojo/bitsdojo_window#45]
bitsdojo_window ^0.0.9 requires plugin_platform_interface ^1.0.1, which is not compatible with other plugins that depend on plugin_platform_interface ^2.0.0

**Comment by bitsdojo** [comment]
Fixed by https://github.com/bitsdojo/bitsdojo_window/commit/3fd4412c7b071e257b3ff33c863438ad358049ab
