### ISSUE TITLE
Windows 10 error

### ISSUE THREAD

**Issue by Danau5tin** [bitsdojo/bitsdojo_window#60]
`[ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol (127)
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:31:29)
#1      bitsdojoWindowAPI (package:bitsdojo_window_windows/src/native_api.dart:66:6)
#2      bitsdojoWindowAPI (package:bitsdojo_window_windows/src/native_api.dart)
#3      _publicAPI (package:bitsdojo_window_windows/src/native_api.dart:69:42)
#4      _publicAPI (package:bitsdojo_window_windows/src/native_api.dart)
#5      _setWindowCanBeShown (package:bitsdojo_window_windows/src/native_api.dart:29:5)
#6      _setWindowCanBeShown (package:bitsdojo_window_windows/src/native_api.dart)
#7      setWindowCanBeShown (package:bitsdojo_window_windows/src/native_api.dart:30:41)
#8      BitsdojoWindowWindows.doWhenWindowReady.<anonymous closure> (package:bitsdojo_window_windows/src/bitsdojo_window_windows_real.dart:19:7)
#9      _rootRunUnary (dart:async/zone.dart:1362:47)
#10     _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:733:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:539:5)
#15     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:577:7)
#16     _rootRun (dart:async/zone.dart:1354:13)
#17     _CustomZone.run (dart:async/zone.dart:1258:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)`

Despite the above stacktrace the programme is still running as expected as far as I can see. Windows 10.

**Comment by alionour** [comment]
Same issue here but the app not rendering

**Comment by bitsdojo** [comment]
Do you have a sample repository that I can test with? Please also specify Flutter version.
