### ISSUE TITLE
How to remove background color?

### ISSUE THREAD

**Issue by RHSaliya** [bitsdojo/bitsdojo_window#63]
How to remove background color of window?
![image](https://user-images.githubusercontent.com/46835920/116976655-15e5d380-acdf-11eb-8e34-2704e238c288.png)

**Comment by RHSaliya** [comment]
Also there is a white line on the top.
![image](https://user-images.githubusercontent.com/46835920/116976824-4168be00-acdf-11eb-8b58-fa7eafae880d.png)

**Comment by tomassasovsky** [comment]
Hey! Please check if there is no issue referencing this problem before opening a new one. This is a duplicate of #12
