### ISSUE TITLE
Suggestion: Add button for GTK

### ISSUE THREAD

**Issue by MalcolmMielle** [bitsdojo/bitsdojo_window#65]
Hi the package looks great can't wait to use it on Linux when it's available.

I was wondering if it would be possible to add buttons on the title bar to follow the Gnome guidelines: https://developer.gnome.org/hig/stable/patterns.html.en

**Comment by MalcolmMielle** [comment]
Just realize that you actually can... :)

**Comment by TaylorHo** [comment]
I'm trying to implement the GTK buttons on Linux, but actually, I can only implement Windows Buttons :/

Can you comment here an example of implementing the GTK theme for buttons??

**Comment by MalcolmMielle** [comment]
It was a while back so I don't remember but I was working with [adwaita](https://pub.dev/packages/adwaita) package and [libawaita](https://pub.dev/packages/libadwaita) packages

**Comment by TaylorHo** [comment]
Just for the record:

I used the [libadwaita](https://pub.dev/packages/libadwaita) package to create the buttons, using the bitsdojo_window functions to minimize, maximize and close the window.

Example:
```
import 'dart:io';

import 'package:bitsdojo_window/bitsdojo_window.dart';
import 'package:flutter/material.dart';
import 'package:libadwaita/libadwaita.dart';

//other pieces of code...

Widget _windowsOrLinuxButtons() {
  return Row(
    children: Platform.isWindows
        ? [
            MinimizeWindowButton(colors: buttonColors),
            MaximizeWindowButton(colors: buttonColors),
            CloseWindowButton(colors: buttonColors),
          ]
        : [
            SizedBox(
              width: 22,
              child: AdwButton.circular(
                child: const Icon(Icons.minimize, size: 12),
                onPressed: () => {appWindow.minimize()},
              ),
            ),
            const SizedBox(width: 5),
            SizedBox(
              width: 22,
              child: AdwButton.circular(
                child: const Icon(Icons.square_outlined, size: 12),
                onPressed: () => {appWindow.maximizeOrRestore()},
              ),
            ),
            const SizedBox(width: 5),
            SizedBox(
              width: 22,
              child: AdwButton.circular(
                child: const Icon(Icons.close_sharp, size: 15),
                onPressed: () => {appWindow.close()},
              ),
            ),
            const SizedBox(width: 10),
          ],
  );
}
```

The [libadwaita](https://pub.dev/packages/libadwaita) package appears to have a bitsdojo_ready implementation for the topbar: [libadwaita_bitsdojo](https://pub.dev/packages/libadwaita_bitsdojo).
I didn't use it because it doesn't apply to my project.
