### ISSUE TITLE
how to custom the window button icon?

### ISSUE THREAD

**Issue by WilliamMiaoC** [bitsdojo/bitsdojo_window#66]

**Comment by sekkit** [comment]
plz support min/max/restore icon styling with images(even svg img)

**Comment by WilliamMiaoC** [comment]
> plz support min/max/restore icon styling with images(even svg img)

Can you give me an example

**Comment by sekkit** [comment]
> > plz support min/max/restore icon styling with images(even svg img)
> 
> Can you give me an example
Here is a sample of XP luna theme files.
[svg.zip](https://github.com/bitsdojo/bitsdojo_window/files/6488787/svg.zip)

**Comment by WilliamMiaoC** [comment]
> > > plz support min/max/restore icon styling with images(even svg img)
> > 
> > 
> > Can you give me an example
> > Here is a sample of XP luna theme files.
> > [svg.zip](https://github.com/bitsdojo/bitsdojo_window/files/6488787/svg.zip)

Maybe I didn't express it clearly. I mean how this plugin (bitsdojo_window) how to change the minimize button and other WindowBotton

**Comment by sekkit** [comment]
plz ask the developer to do that.

**Comment by bitsdojo** [comment]
Hi there,

You can use any widget you like for minimize/maximize/restore. Simply use these functions in your onPressed handler:

### Close the window:

`appWindow.close`

### Minimize the window:

`appWindow.minimize`

### Maximize/restore the window:

`appWindow.maximizeOrRestore`
