### ISSUE TITLE
Not supported in Windows 8 or Windows 8.1 ?

### ISSUE THREAD

**Issue by Grigary-C-Antony** [bitsdojo/bitsdojo_window#67]

**Comment by kirill-21** [comment]
Only Windows 10. https://github.com/bitsdojo/bitsdojo_window/issues/53

**Comment by UNIcodeX** [comment]
Does anyone know if this is being actively worked on?

Would that be why I get a bunch of errors about Dpi identifiers not being found?

**Comment by bitsdojo** [comment]
Hi there.

Yes, this is on my list. Lack of free time is the only reason why this is not fixed yet.

Ideally I would love to work full time on this package but haven't yet figured out how to do it in a sustainable way.

**Comment by iampopal** [comment]
Waiting for a fix for this issue?

**Comment by kirill-21** [comment]
> Waiting for a fix for this issue?

Yes, we are waiting

**Comment by bitsdojo** [comment]
Please follow https://github.com/bitsdojo/bitsdojo_window/issues/53 for updates.

This is coming in the next release.
