### ISSUE TITLE
Made ReadMe More Clear

### ISSUE THREAD

**Issue by Alexandre2006** [bitsdojo/bitsdojo_window#73]
Hey there!

While using this in my new flutter project, I noticed the ReadMe stated that BDW_HIDE_ON_STARTUP should be added. 

This is false, and I believe it could cause some confusion with new users. Adding BDW_HIDE_ON_STARTUP closes the window as soon as it opens, preventing the user from doing anything, even creating a new window, since the application gets terminated because the window was closed.

The library works fine without BDW_HIDE_ON_STARTUP, so I created a pull request ( #68 ) to prevent confusion.

Please review the pull request #68 have a great day!

**Comment by kirill-21** [comment]
Well, that's an absolutely normal behavior. Use
```
doWhenWindowReady(() {
    appWindow.alignment = Alignment.center;
    appWindow.show();
  });
```
to show the window as soon as it's ready

'BDW_HIDE_ON_STARTUP' flag does not 'closes the window as soon as it opens', it never shows it until you call a show function
