### ISSUE TITLE
Broken after the ^0.1.1 and ^0.1.1+1 update

### ISSUE THREAD

**Issue by Shamik07** [bitsdojo/bitsdojo_window#75]
Because no versions of bitsdojo_window_linux match 0.1.1 and no versions of bitsdojo_window_linux match >0.1.1 <0.2.0, bitsdojo_window_linux ^0.1.1 is forbidden.
So, because my_app depends on bitsdojo_window ^0.1.1+1 which depends on bitsdojo_window_linux ^0.1.1, version solving failed.
pub get failed (1; So, because my_app depends on bitsdojo_window ^0.1.1+1 which depends on bitsdojo_window_linux ^0.1.1, version solving failed.)

**Comment by bitsdojo** [comment]
How does your `pubspec.yaml` file look like?

**Comment by Shamik07** [comment]
Its just the default starter counter app 

```
name: delete_app_2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  bitsdojo_window: ^0.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.3

flutter:
  uses-material-design: true

**Comment by Shamik07** [comment]
flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 2.3.0-16.0.pre, on Microsoft Windows [Version 10.0.19042.985], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
[√] Android Studio (version 4.2.0)
[√] VS Code (version 1.56.2)
[√] Connected device (3 available)

• No issues found!

**Comment by Shamik07** [comment]
I had to revert to ^0.1.0+1 to get it working

**Comment by bitsdojo** [comment]
Tried with a sample counter app and the same Flutter version but could not reproduce it on my system.

If you have a sample repo that I can clone to reproduce this and further investigate it, feel free to re-open this.
