### ISSUE TITLE
Missing shadow on Linux window

### ISSUE THREAD

**Issue by jesusrp98** [bitsdojo/bitsdojo_window#77]
Linux apps that uses GTK usually have a shadow behind them, that is missing in the current implementation.

![image](https://user-images.githubusercontent.com/8961959/121384739-d39c5b80-c948-11eb-9da4-f49a9294878a.png)

This is a photo of a typical GTK app:

![image](https://user-images.githubusercontent.com/8961959/121384978-021a3680-c949-11eb-823f-25129c448fcf.png)

**Comment by bitsdojo** [comment]
Thank you for reporting it. Added to my list.

**Comment by jesusrp98** [comment]
The `gtk_window_set_decorated()` function inside the `gtk` library not only removed any kind of header bar or window border, but also its shadow.

This is where this function is called within the project:
`window_impl.cpp`:
``` c
  void setCustomFrame(gboolean value) {
      if (false == value) {
          return;
      }
      auto window = this->handle;
      auto screen = gtk_window_get_screen(window);
      gtk_window_set_decorated(window, FALSE); <<-- this
      auto rgba = gdk_screen_get_rgba_visual(screen);
      if (rgba && gdk_screen_is_composited(screen)) {
          gtk_widget_set_visual(GTK_WIDGET(window), rgba);
      }

      auto *backgroundStyle = gtk_css_provider_new();
      gtk_css_provider_load_from_data(GTK_CSS_PROVIDER(backgroundStyle),
                                      "window {\n"
                                      "   background:none;\n"
                                      "}\n",
                                      -1, NULL);
      gtk_style_context_add_provider_for_screen(
          screen, GTK_STYLE_PROVIDER(backgroundStyle),
          GTK_STYLE_PROVIDER_PRIORITY_APPLICATION);
      g_object_unref(backgroundStyle);
  }
```

**Comment by bitsdojo** [comment]
Merging this with https://github.com/bitsdojo/bitsdojo_window/issues/97

Please follow that one for updates.
