### ISSUE TITLE
Anyway to play nice with `menubar` plugin?

### ISSUE THREAD

**Issue by esDotDev** [bitsdojo/bitsdojo_window#8]
When disabling the native chrome, we also lose this menu, which is unfortunate.
https://github.com/google/flutter-desktop-embedding/tree/master/plugins/menubar

I'm guessing the answer is no, but is there any way to position the widget bar above the file menu, while still hiding the top-chrome?
![image](https://user-images.githubusercontent.com/736973/101750270-05149700-3a8c-11eb-9804-1767d6388076.png)

**Comment by bitsdojo** [comment]
Hi Shawn,

As you guessed, unfortunately the answer is no.

I am curious: is there any reason why you would not implement the menu using Flutter widgets?

**Comment by esDotDev** [comment]
Just a matter of flexibility, like it would be nice if using Custom chrome did not necessitate custom menus.

I don't think it would be a ton of work to create our own, but there is quite a bit of functionality baked in with expanding/collasping sub menus, keyboard controls, and shortcuts. 

We're currently making an app that shows off all the 'easy wins' on desktop, so we were hoping to combine some custom chrome, with native menus. I guess not, but totally makes sense  :'(
