### ISSUE TITLE
ticker is disposed but still get error maximize window in desktop flutter

### ISSUE THREAD

**Issue by snorliman** [bitsdojo/bitsdojo_window#85]
info about error: "The following assertion was thrown while finalizing the widget tree:
_CalibrationCustomState#c6f06(tickers: tracking 1 ticker) was disposed with an active Ticker.

_CalibrationCustomState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak."

in my code i have dispose stream and animation but still with maximize window i got this error

**Comment by bitsdojo** [comment]
Hi there,

Do you have a sample repository that I can use to test this?

**Comment by snorliman** [comment]
Thank you for answer:) but I go to new updated version of Flutter and updated Android Studio and now this issue is gone:) I will test more, if where is for sure, but now when I maximize window the error is not showing up:)
