### ISSUE TITLE
Add styling options for native toolbar

### ISSUE THREAD

**Issue by esDotDev** [bitsdojo/bitsdojo_window#9]
Given the limitations here: https://github.com/bitsdojo/bitsdojo_window/issues/8, it could be nice if there was an API so we can change the color of the native top btns and window bar. Is that possible?

It's really like 3 colors that need to be set to get a much nicer look and match app themes.
![image](https://user-images.githubusercontent.com/736973/101809826-42514700-3ad5-11eb-8e09-0f4ec0baeb2b.png)

**Comment by bitsdojo** [comment]
Unfortunately, Windows does not offer any clean API to change the color of the native top buttons and window bar so that is the main limitation when trying to implement something like this.

**Comment by esDotDev** [comment]
Haha, ya that makes sense! Also explains why I can find literally 0 examples of windows app with custom toolbars, using native menu_bar. Ah well, fact of life I guess :) Thanks for the quick response!
