### ISSUE TITLE
[Linux] Window has no caption

### ISSUE THREAD

**Issue by giaur500** [bitsdojo/bitsdojo_window#91]
I run your sample, but I'm getting window without any caption. Caption is visible on taskbar, but window itself has now any title/caption:
![image](https://user-images.githubusercontent.com/26817206/126623519-f51821fc-c930-4d07-82a7-dc9916e7bd3c.png)

I think this is a bug, because caption is set in code. Window without any title is not much useful.

**Comment by bitsdojo** [comment]
HI there,

You can use any Flutter widget to display the window caption. 

Is there a specific functionality that you’re interested in?

**Comment by j0chn1** [comment]
I faced the same issue. 
There is no app title within the border. 
I added a Text to display it but this creates an area which is not draggable.
Is there a way to add a text to the border which is centered and draggable

**Comment by j0chn1** [comment]
Forget it, after checkung the construcotr i saw that you can ywap the default widget with a custom one.
