### ISSUE TITLE
is it possible to support windows 7 which has no GetSystemMetricsForDpi and GetDpiForWindow API?

### ISSUE THREAD

**Issue by skydig** [bitsdojo/bitsdojo_window#92]
thanks for you splendid plugin!

**Comment by Maged12** [comment]
i have the same inquire

**Comment by bitsdojo** [comment]
This is a duplicate of https://github.com/bitsdojo/bitsdojo_window/issues/53

Will be fixed in the next release. Please follow that issue for updates.
