### ISSUE TITLE
Windows 11 Support?

### ISSUE THREAD

**Issue by portlek** [bitsdojo/bitsdojo_window#99]
I tested my project on a Windows 10 device it's working well but I've just installed a Windows 11 ISO and It's not working what I expect.

![image](https://user-images.githubusercontent.com/12835420/131253939-d23c17ca-3c1d-4fa3-9827-42fb6c4ee031.png)

(I couldn't remove this windows bar)

**Comment by bitsdojo** [comment]
Thanks for reporting it.

Didn't get a chance to install Windows 11 but I will keep this issue for tracking progress on Windows 11 support.

**Comment by alexmercerind** [comment]
This actually works flawless on Windows 11. One can have my confirmation.
